stages:
  - test
  - docker_image
  - deploy

job_test:
  stage: test
  script: echo 'test'

job_build_and_push:
  stage: docker_image
#  image: docker:20.10.16-dind
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    DOCKER_TLS_CERTDIR: ""
#  services:
#    - docker:20.10.16-dind
#  before_script:
#    - echo 'before_script'
#    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN $DOCKERHUB_REGISTRY
  script:
    - echo 'docker_image'
#    - docker build --tag $DOCKERHUB_REGISTRY:$CI_COMMIT_TAG --tag $DOCKERHUB_REGISTRY:latest .
#    - dokcer push $DOCKERHUB_REGISTRY:$CI_COMMIT_TAG
#    - dokcer push $DOCKERHUB_REGISTRY:latest

job_deploy:
  stage: deploy
#  before_script:
#    - docker login -u "DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN" $DOCKERHUB_REGISTRY
  script:
    - echo 'deploy'
#    - docker run -itd -p 8000:8000 --name libm porkerll/libm
