# Generated by Django 3.2.9 on 2022-08-07 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBSN', models.CharField(default='', max_length=256)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('author', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
                ('pubdate', models.DateField()),
                ('stock_all', models.IntegerField(default=0)),
                ('stock_now', models.IntegerField(default=0)),
                ('borrow_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('p_num', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('chapters', models.CharField(max_length=6666)),
                ('description', models.CharField(max_length=6666)),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
        migrations.CreateModel(
            name='libCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(default='', max_length=1024)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='libComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('p_num', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libbook')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='libUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='default', max_length=256)),
                ('account', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('type', models.IntegerField(default=2)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('change_password_required', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('男', 'man'), ('女', 'woman'), ('保密', 'unknown')], default='unknown', max_length=32)),
                ('birthday', models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('l_time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='libMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024)),
                ('message', models.CharField(max_length=1024)),
                ('c_time', models.DateField(auto_now_add=True)),
                ('readed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libuser')),
            ],
        ),
        migrations.CreateModel(
            name='libConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1024)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libuser')),
            ],
        ),
        migrations.CreateModel(
            name='libCommentFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libuser')),
            ],
        ),
        migrations.AddField(
            model_name='libcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libuser'),
        ),
        migrations.CreateModel(
            name='libBookFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libuser')),
            ],
        ),
        migrations.CreateModel(
            name='libBookCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libuser')),
            ],
        ),
        migrations.AddField(
            model_name='libbook',
            name='categ',
            field=models.ManyToManyField(to='libFront.libCategory'),
        ),
        migrations.CreateModel(
            name='libBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_time', models.DateTimeField(auto_created=True)),
                ('c_time', models.DateTimeField()),
                ('p_time', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libuser')),
            ],
            options={
                'verbose_name': '还书记录',
                'verbose_name_plural': '还书记录',
            },
        ),
        migrations.CreateModel(
            name='libAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024)),
                ('content', models.CharField(max_length=1024)),
                ('type', models.IntegerField(default=2)),
                ('c_time', models.DateField(auto_now_add=True)),
                ('readed', models.BooleanField(default=False)),
                ('for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_user', to='libFront.libuser')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='libFront.libuser')),
            ],
        ),
    ]
