# Generated by Django 3.2.9 on 2021-12-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libFront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='libConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1024)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libFront.libuser')),
            ],
        ),
    ]
