# Generated by Django 3.2.9 on 2021-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libFront', '0002_libconfirmstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='libuser',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
